# Generated by Django 5.2.6 on 2026-02-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_performance_indexes'),
        ('product', '0011_alter_variation_variation_category'),
    ]

    operations = [
    ]
