# Generated by Django 5.2.6 on 2026-02-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_merge_20260216_1146'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_product_slug_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_is_available_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='reviewrating',
            name='review_product_idx',
        ),
        migrations.RemoveIndex(
            model_name='reviewrating',
            name='review_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='reviewrating',
            name='review_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='variation',
            name='variation_product_idx',
        ),
    ]
