# Generated by Django 5.2.6 on 2026-02-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_performance_indexes'),
        ('orders', '0008_merge_20260213_2136'),
    ]

    operations = [
    ]
