# Generated by Django 5.2.6 on 2026-02-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_merge_20260216_1145'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_order_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_is_ordered_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderproduct',
            name='orderproduct_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderproduct',
            name='orderproduct_product_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderproduct',
            name='orderproduct_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_payment_id_idx',
        ),
    ]
