# Generated by Django 5.2.6 on 2026-02-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_performance_indexes'),
        ('cart', '0005_checkoutdb_delivery_area'),
    ]

    operations = [
    ]
