# Generated by Django 5.2.6 on 2026-02-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_merge_20260216_1147'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitems',
            name='cartitems_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitems',
            name='cartitems_product_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitems',
            name='cartitems_cart_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitems',
            name='cartitems_is_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='checkoutdb',
            name='checkoutdb_user_idx',
        ),
    ]
